package org.ng.undp.vdms.views;

import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.ng.undp.vdms.configs.AutowireHelper;
import org.ng.undp.vdms.dao.Accessor;
import org.ng.undp.vdms.dao.Filter;
import org.ng.undp.vdms.domains.User;
import org.ng.undp.vdms.domains.Vendor;
import org.ng.undp.vdms.services.security.RoleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.servlet.view.document.AbstractXlsView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Created by macbook on 7/7/17.
 */
public class ExcelViewVendors extends AbstractXlsView {

    @Autowired
    private RoleService roleService;

    @SuppressWarnings("unchecked")
    @Override
    protected void buildExcelDocument(Map<String, Object> model,
                                      Workbook workbook,
                                      HttpServletRequest request,
                                      HttpServletResponse response) throws Exception {

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd - MM - yyyy hh:mm:ss a");

        // change the file name
        response.setHeader("Content-Disposition", "attachment; filename=\"vdms-vendors-file.xls\"");
        List<Vendor> users = null;


        //Type of vendor
        String vendorType = request.getParameter("type");

        if (vendorType == null) {
            users = Accessor.findList(Vendor.class, Filter.get().field("user.deleted_at").isNull().field("deleted_at").isNull().field("suspended", false));
        } else {

            users = Accessor.findList(Vendor.class, Filter.get().field("user.deleted_at").isNull().field("deleted_at").isNull().field("suspended", false).field("user.roles").contains(getUserRoleID(vendorType)));

        }
        // create excel xls sheet
        Sheet sheet = workbook.createSheet("Vendors");
        sheet.setDefaultColumnWidth(30);

        // create style for header cells
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setFontName("Arial");

        //20 * 12 for 14px
        font.setFontHeight((short) (20 * 12));

        style.setFillForegroundColor(HSSFColor.WHITE.index);
        //style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        //font.setBold(true);
        font.setColor(HSSFColor.BLACK.index);
        style.setFont(font);


        CellStyle style1 = workbook.createCellStyle();
        Font font1 = workbook.createFont();
        font1.setFontName("Arial");


        style1.setFillForegroundColor(HSSFColor.GREEN.index);
        style1.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        font1.setBold(true);
        font1.setColor(HSSFColor.WHITE.index);

        //20 * 14 for 14px
        font1.setFontHeight((short) (20 * 14));
        style1.setFont(font1);
        style1.setLocked(true);

        // create header row
        Row header = sheet.createRow(0);
        header.createCell(0).setCellValue("Name");
        header.getCell(0).setCellStyle(style1);
        header.createCell(1).setCellValue("VPA");
        header.getCell(1).setCellStyle(style1);

        header.setHeight((short) 600);


        //header.setRowStyle(style1);


        int rowCount = 1;
        int lastRow = 0;

        for (Vendor user : users) {
            Row userRow = sheet.createRow(rowCount++);
            userRow.createCell(0).setCellValue(user.getName());
            userRow.getCell(0).setCellStyle(style);
            userRow.createCell(1).setCellValue(user.getVpa().toString());
            userRow.getCell(1).setCellStyle(style);

            lastRow = rowCount;


        }


        CellStyle editableStyle = workbook.createCellStyle();
        editableStyle.setLocked(true);
        editableStyle.setWrapText(true);
        editableStyle.setShrinkToFit(true);

        Row userRow = sheet.createRow(lastRow + 1);
        Cell c = userRow.createCell(0);
        c.setCellStyle(style1);

        c.setCellValue("Generated By VDMS -   " + simpleDateFormat.format(new Date()));
        userRow.createCell(1).setCellStyle(style1);

        userRow.setHeight((short) 400);

        //firstrow , lastrow ,firstcol, lastcol for merge

        sheet.addMergedRegion(new CellRangeAddress(lastRow, lastRow, 0, 1));


    }

    private Long getUserRoleID(String role) {
        AutowireHelper.autowire(this, this.roleService);
        logger.info("The role is : " + role.trim().toUpperCase());
        Long roleID = roleService.findByName(role.trim().toUpperCase()).getId();

        logger.info(roleID);
        return roleID;
    }

}
